### ISSUE TITLE
Use different date for each post

### ISSUE THREAD

**Issue by pathawks** [jekyll/benchmarking#9]
From #4:

> Should we decrement dates by a day?
> 
> Yes, that would be best, because a real site would have posts published on the same day and over multiple days.. So, if there's a performance sink somewhere, we need to be aware of it's existence..

I don't know if this can be (easily) done from Bash. Might be best to port this all over to a Rake task?

**Comment by mattr-** [comment]
Different dates should not matter from a post generation standpoint. I think we can punt on this for now.

**Comment by mattr-** [comment]
Sorry. Still waking up. Let me clarify further.

I think it's a great idea to push the date back by a day for posts so we ensure that they get published. I don't think it's beneficial - at the moment - to do a single post per day, as the date the post is created doesn't matter from a generation standpoint, and that was the original point of this repo.

**Comment by pathawks** [comment]
There has been some talk of caching Dates so we don’t have to call `Date.parse` as frequently. If all posts share the same date, this would have an outsized impact.

**Comment by mattr-** [comment]
Wouldn't we just cache dates per post then? Parse it once, cache it, and then you're done?

**Comment by pathawks** [comment]
Seems reasonable. Maybe @ashmaroli can weigh in?

**Comment by ashmaroli** [comment]
I don't see the logic behind caching date on a real site because, posts published on the same day may be at differing times.. So the check to see if *dates* for two posts are the same can lead to performance drops instead of soars..
(On CI, all files are created/modified at the same instant during a `git clone`)

I have a proposal open at jekyll/jekyll where `Date.parse` is going to be called only once.. the downside being users will no longer be given a pinpoint message stating where the given date is incorrect (in `fllename` / `front matter` / `front matter defaults`)

**Comment by ashmaroli** [comment]
er.. um.. so no differing dates?

**Comment by pathawks** [comment]
@ashmaroli Sorry, I read your comment to mean that this is unnecessary. Did I misunderstand?

**Comment by ashmaroli** [comment]
I meant to say caching post date per post may lead to erroneous reports..

**Comment by mattr-** [comment]
If we're caching post date per post, we'll just be associating the parsed date with the post and referencing that instead of calling `Date.parse` all the time for every post. How would that lead to erroneous reports?

**Comment by ashmaroli** [comment]
> instead of calling `Date.parse` all the time for every post

I fail to see the benefit of adding optimization in benchmarking code for a hypothetical site, while the core library still contains non-optimized code that will be run against real-world sites..
Please enlighten me..

**Comment by mattr-** [comment]
The proposed optimization was not for the benchmarking code but for the core library. :smile:

**Comment by ashmaroli** [comment]
> but for the core library

Ah.. I see..
It would benefit users setting date via `front matter defaults` (one value of date for all documents of given type..)
:+1:

**Comment by pathawks** [comment]
Originally, each post _was_ generated on a different date:

https://github.com/jekyll/benchmarking/blob/67349aab5505fb797f40f3a2506b736ffaaa18a1/generate_site.sh#L45

**Comment by DirtyF** [comment]
I made a quick test and I didn't notice any big differences with or without different dates on 1000 posts.
Around 25s for both on my machine.

**Comment by ashmaroli** [comment]
@DirtyF that's because there isn't any optimization in place right now.. It's still yet-to-be-added in the core..
